// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqtFJoHJ_qraOEpWPftVLvfXRfG71NBLU',
    appId: '1:188052832226:web:4327213e17f3134bfb43bb',
    messagingSenderId: '188052832226',
    projectId: 'ubs-23a56',
    authDomain: 'ubs-23a56.firebaseapp.com',
    storageBucket: 'ubs-23a56.appspot.com',
    measurementId: 'G-TJJLD4WW08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqIaoWPiXoSGbflne2iEyI4ocRqV3ETU',
    appId: '1:188052832226:android:90151a618e9ba01ffb43bb',
    messagingSenderId: '188052832226',
    projectId: 'ubs-23a56',
    storageBucket: 'ubs-23a56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2E3NBxRB2JHIOkqdsR6IKZieGMMieGSo',
    appId: '1:188052832226:ios:8ef309575bd9b0b8fb43bb',
    messagingSenderId: '188052832226',
    projectId: 'ubs-23a56',
    storageBucket: 'ubs-23a56.appspot.com',
    iosBundleId: 'com.example.ubs',
  );
}
